#!/bin/bash

for i in "${1}"/* "${1}"/.*; do
	bn="$(basename "${i}")"
	[[ "${bn}" == "." || "${bn}" == ".." || "${bn}" == "*" ]] && continue
	dest="${2}/${bn}"
	mkdir -p "$(dirname "${dest}")"
	ls -snTf "$(pwd)/${i}" "${dest}"
done
